### ISSUE TITLE
[PE-D][Tester A] Unable to plan a same-day trip

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W11-4/tp#189]
Steps to reproduce:
1. Add an itinerary of 0 days for a day trip (`add d/Day Trip c/Singapore sd/2022-10-28 du/0 p/3 b/1000 `)

![image.png](https://raw.githubusercontent.com/ElijahS67/ped/master/files/5dc2b9e5-1ff4-4d4c-b674-0cc9dd33d2c9.png)

2. Select the itinerary (`select 1`)
3. Add an item (`add d/go sentosa du/10`)
4. Plan the item on any day, including `d/0` or `d/1` (`plan 1 d/1 st/12:00`)  

Expected: Able to plan the item on either day 0 or day 1  
Actual: Unable to plan the item as there are no days available (even though a same-day trip should be considered as a day)

![image.png](https://raw.githubusercontent.com/ElijahS67/ped/master/files/74593bec-fa9f-4b7d-a51f-e764e6945860.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ElijahS67/ped#7

**Comment by CFSY** [comment]
Need to change end date to start date + (duration - 1)
Need to disallow 0 days duration
